### ISSUE TITLE
pcp-pmda-lio on Ubuntu 18.04 LTS errors on "Install"

### ISSUE THREAD

**Issue by hydro-b** [pcuzner/pcp-pmda-lio#1]
I'm trying to get a Ceph iSCSI target running on Ubuntu 18.04 (http://docs.ceph.com/docs/master/rbd/iscsi-overview/). All parts succeeded (three gateways up-and-running with two nodes on CentOS 7.5 and one node on Ubuntu 18.04 LTS) but the monitoring part. Trying to "./Install" in /var/lib/pcp/pmdas/lio results in the following message:

 ./Install 
Updating the Performance Metrics Name Space (PMNS) ...
Terminate PMDA if already installed ...
Updating the PMCD control file, and notifying PMCD ...
Waiting for pmcd to terminate ...
Starting pmcd ... [Mon May 21 08:21:45] pmcd(12453) Error: __pmGetAddrInfo(redaced_hostname_here), Unknown host 
Check lio metrics have appeared ... 12 metrics and 0 values

The "lio.log":

 cat lio.log 
Log for pmdalio on redacted_hostname_here started Sun May 20 23:42:14 2018

[Sun May 20 23:42:16] pmdalio(20488) Error: pduread: select() on fd=0 status=-4: Interrupted system call
[Sun May 20 23:42:16] pmdalio(20488) Critical: __pmdaSetupPDU: PMDA pmdalio getting creds: Interrupted system call
Traceback (most recent call last):
  File "pmdalio.python", line 320, in <module>
    LIOPMDA("lio", 142).run()
  File "pmdalio.python", line 87, in __init__
    self.connect_pmcd()
  File "/usr/lib/python2.7/dist-packages/pcp/pmda.py", line 309, in connect_pmcd
    cpmda.connect_pmcd()
KeyboardInterrupt

As far as I can see all python dependencies have been fulfilled:

- python-rtslib-fb 2.1.57+debian-4
- python3-rtslib-fb 2.1.57+debian-4
- python-pcp 4.0.1-1
- python3-pcp 4.0.1-1
- pcp 4.0.1-1
- libpcp-gui2 4.0.1-1
- libpcp-import1 4.0.1-1
- libpcp-mmv1 4.0.1-1
- libpcp-pmda-perl 4.0.1-1
- libpcp-pmda3 4.0.1-1
- libpcp-trace2 4.0.1-1
- libpcp-web1 4.0.1-1
- libpcp-gui2 4.0.1-1
- libpcp-import1 4.0.1-1
- libpcp-mmv1 4.0.1-1
- libpcp-pmda-perl 4.0.1-1
- libpcp-pmda3 4.0.1-1
- libpcp-trace2 4.0.1-1
- libpcp-web1 4.0.1-1
- libpcp3 libpcp3 4.0.1-1

This might be a python 2 versus 3 thing, I'm not sure.

**Comment by hydro-b** [comment]
This turned out to be a "missing" IPv4 address on the iSCSI target.

**Comment by pcuzner** [comment]
This project was merged into the main pcp project a while back - so these days the lio pmda should already be available within your distro. However, for some reason 18.04 doesn't ship it! It's in the rpm based distros (fedora, CentOS, OpenSuSE)
